"""modelo base: usuarios, perfiles, objetivos, mensajes

Revision ID: e53021b245a1
Revises: 
Create Date: 2026-09-22 01:48:32.519300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53021b245a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telefono_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_telefono_whatsapp'), 'usuarios', ['telefono_whatsapp'], unique=True)
    op.create_table('mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('USUARIO', 'ASISTENTE', name='rol_mensaje_enum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_fecha'), 'mensajes', ['fecha'], unique=False)
    op.create_index(op.f('ix_mensajes_usuario_id'), 'mensajes', ['usuario_id'], unique=False)
    op.create_table('objetivos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('BAJAR_PESO', 'GANAR_MUSCULO', 'RENDIMIENTO_DEPORTIVO', 'SALUD_GENERAL', name='tipo_objetivo_enum'), nullable=False),
    sa.Column('peso_objetivo_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_objetivo', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('altura_cm', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', name='sexo_enum'), nullable=True),
    sa.Column('condiciones_medicas', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfiles')
    op.drop_table('objetivos')
    op.drop_index(op.f('ix_mensajes_usuario_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_fecha'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_usuarios_telefono_whatsapp'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
